// ─────────────────────────────────────────────────────────────
// 컨셉 스킨: 무협
// fantasy.mjs · scifi.mjs 와 "완전히 같은 구조". 이름/표현만 무협으로.
// → 같은 시스템이 또 다른 게임처럼 보이는 세 번째 스킨.
// ─────────────────────────────────────────────────────────────

export const wuxiaConcept = {
  id: 'wuxia',
  title: '무림비록',
  palette: { primary: '#8a2b2b', accent: '#e0b64a' },

  archetypes: {
    VANGUARD: { name: '철갑수', emoji: '🛡️' },
    STRIKER: { name: '검객', emoji: '⚔️' },
    SUPPORT: { name: '의원', emoji: '🌿' },
    ROGUE: { name: '자객', emoji: '🗡️' },
    ARCHER: { name: '궁사', emoji: '🏹' },
    MAGE: { name: '술사', emoji: '☯️' },
  },

  resources: {
    currency: { name: '냥', emoji: '🪙' },
    growth: { name: '내공', emoji: '🌀' },
    summon: { name: '비급', emoji: '📜' },
    gem: { name: '영옥', emoji: '💎' },
  },

  terms: { unit: '협객', party: '문파', stage: '관', energy: '기력' },

  // 속성 ID(Core) → 무협 표시명. fantasy/scifi와 "같은 ID, 다른 이름".
  elements: {
    FIRE: { name: '화', emoji: '🔥' },
    WATER: { name: '수', emoji: '💧' },
    WOOD: { name: '목', emoji: '🌿' },
    LIGHT: { name: '양', emoji: '☀️' },
    DARK: { name: '음', emoji: '🌑' },
  },

  // 도감 — fantasy/scifi와 "완전히 같은 mechanical 구조"(archetype/rarity/signature/element 동일),
  // 이름/외형/말투만 무협으로. 같은 시스템·같은 캐릭터 슬롯, 다른 인물.
  roster: [
    { id: 'kael', name: '염호', emoji: '🔥', title: '화염검객', personality: '불같은', element: 'FIRE', archetype: 'STRIKER', rarity: 'SSR', signature: 'SIG_FLAME_EDGE',
      lines: { greet: '가자, 검으로 태워버리마!', bond: '너와 함께라면 어떤 적도 두렵지 않다.', levelup: '내공이 끓어오른다!' } },
    { id: 'luna', name: '월아', emoji: '🌙', title: '월광의선', personality: '자애로운', element: 'LIGHT', archetype: 'SUPPORT', rarity: 'SSR', signature: 'SIG_MOON_BLESSING',
      lines: { greet: '…오늘도 무탈하시길.', bond: '곁에 계셔 주시니 든든하옵니다.', levelup: '월광의 기운이 깃드옵니다.' } },
    { id: 'gwen', name: '빙벽', emoji: '❄️', title: '한빙수호', personality: '과묵한', element: 'WATER', archetype: 'VANGUARD', rarity: 'SR', signature: 'SIG_FROST_GUARD',
      lines: { greet: '…왔는가.', bond: '너는… 믿을 만하다.', levelup: '기반이 더 단단해졌다.' } },
    { id: 'ciel', name: '청풍', emoji: '🌪️', title: '표풍검무', personality: '쾌활한', element: 'WOOD', archetype: 'STRIKER', rarity: 'SR', signature: 'SIG_WIND_DANCE',
      lines: { greet: '한 수 놀아볼까~?', bond: '헤헤, 너 정말 마음에 들어!', levelup: '검풍이 더 빨라졌어!' } },
    { id: 'bran', name: '반석', emoji: '🪨', title: '대지방패', personality: '든든한', element: 'WOOD', archetype: 'VANGUARD', rarity: 'R', signature: 'SIG_EARTH_AEGIS',
      lines: { greet: '뒤는 내게 맡겨라.', bond: '내가 너를 지키겠다.', levelup: '더 굳건해졌다.' } },
    { id: 'ael', name: '서광', emoji: '🕊️', title: '예언선인', personality: '신비로운', element: 'LIGHT', archetype: 'SUPPORT', rarity: 'R', signature: 'SIG_LIGHT_ORACLE',
      lines: { greet: '천기가 보이는구나…', bond: '우리 인연은 하늘에 새겨졌지.', levelup: '예지의 힘이 깊어진다.' } },
    { id: 'ara', name: '흑뢰', emoji: '⚡', title: '뇌전검', personality: '거친', element: 'DARK', archetype: 'STRIKER', rarity: 'R', signature: 'SIG_STORM_BLADE',
      lines: { greet: '덤벼라!', bond: '…너, 제법이군.', levelup: '검격이 더 매서워졌다!' } },
    { id: 'mir', name: '소룡', emoji: '🗡️', title: '견습검사', personality: '풋풋한', element: 'WOOD', archetype: 'STRIKER', rarity: 'N', signature: 'SIG_NOVICE',
      lines: { greet: '잘 부탁드립니다!', bond: '저를 제자로 거둬 주십시오!', levelup: '저 강해졌지요?!' } },
    // ── P1 신규: 속성×원형 공백 보강 ──
    { id: 'pyra', name: '홍염', emoji: '🛡️', title: '화염방벽', personality: '굳건한', element: 'FIRE', archetype: 'VANGUARD', rarity: 'SR', signature: 'SIG_EMBER_WALL',
      lines: { greet: '내 뒤는 안전하다.', bond: '내 불길로 너를 지키마.', levelup: '화벽이 뜨겁게 달아오른다!' } },
    { id: 'frost', name: '설랑', emoji: '🧊', title: '빙하자객', personality: '냉정한', element: 'WATER', archetype: 'STRIKER', rarity: 'SR', signature: 'SIG_GLACIER_EDGE',
      lines: { greet: '…끝은 한순간이다.', bond: '너에게만은 칼끝을 거두지.', levelup: '검이 더 날카로워졌다.' } },
    { id: 'marina', name: '벽수', emoji: '🌊', title: '조수의원', personality: '온화한', element: 'WATER', archetype: 'SUPPORT', rarity: 'SR', signature: 'SIG_TIDE_HYMN',
      lines: { greet: '다치신 곳은 없으신지요?', bond: '당신 곁이 제 강물이옵니다.', levelup: '조수의 기운이 차오릅니다.' } },
    { id: 'signe', name: '홍기', emoji: '📯', title: '전열고수', personality: '용맹한', element: 'FIRE', archetype: 'SUPPORT', rarity: 'R', signature: 'SIG_WAR_CHANT',
      lines: { greet: '진격 준비!', bond: '너와 함께라면 두렵지 않다!', levelup: '북소리가 우렁차진다!' } },
    // ── P3 신화(UR) ──
    { id: 'aurel', name: '여명', emoji: '🌟', title: '성검협', personality: '고결한', element: 'LIGHT', archetype: 'STRIKER', rarity: 'UR', signature: 'SIG_DAWNBREAKER',
      lines: { greet: '여명이 어둠을 가른다.', bond: '너의 곁에서 새벽을 지키겠다.', levelup: '검에 서광이 깃든다!' } },
    { id: 'nyx', name: '현음', emoji: '🔮', title: '심연술사', personality: '초연한', element: 'DARK', archetype: 'SUPPORT', rarity: 'UR', signature: 'SIG_ABYSS_ORACLE',
      lines: { greet: '심연이 너를 응시한다.', bond: '네 운명, 내가 지켜보마.', levelup: '천기가 더 깊어진다.' } },
    // ── 신규 원형: 자객·궁사·술사 ──
    { id: 'kai', name: '야묘', emoji: '🥷', title: '풋내기도적', personality: '재빠른', element: 'WOOD', archetype: 'ROGUE', rarity: 'N', signature: 'SIG_ROGUE_NOVICE',
      lines: { greet: '들키기 전에 뜨자!', bond: '너한테는 손 안 대.', levelup: '몸놀림이 빨라졌어!' } },
    { id: 'vera', name: '흑접', emoji: '🔪', title: '암야자객', personality: '냉혹한', element: 'DARK', archetype: 'ROGUE', rarity: 'SSR', signature: 'SIG_NIGHT_FANG',
      lines: { greet: '어둠 속에서 기다렸다.', bond: '…네게만 등을 보이지.', levelup: '더 짙은 어둠이 된다.' } },
    { id: 'robin', name: '녹림', emoji: '🏹', title: '산림궁수', personality: '차분한', element: 'WOOD', archetype: 'ARCHER', rarity: 'R', signature: 'SIG_FOREST_ARROW',
      lines: { greet: '바람의 방향을 읽는다.', bond: '너와는 표적을 나눌 수 있지.', levelup: '조준이 더 정밀해졌다.' } },
    { id: 'sylas', name: '광시', emoji: '💫', title: '광명궁성', personality: '고요한', element: 'LIGHT', archetype: 'ARCHER', rarity: 'SSR', signature: 'SIG_LIGHT_ARROW',
      lines: { greet: '빛은 과녁을 놓치지 않는다.', bond: '네 곁에서 시위를 당기지.', levelup: '화살에 빛이 서린다.' } },
    { id: 'elara', name: '화령', emoji: '🕯️', title: '화염술사', personality: '열정적인', element: 'FIRE', archetype: 'MAGE', rarity: 'R', signature: 'SIG_INFERNO_BOLT',
      lines: { greet: '불꽃이 손끝에서 춤춰요.', bond: '당신 곁이라 더 뜨거워져요.', levelup: '기운이 타오릅니다!' } },
    { id: 'oriel', name: '혼돈', emoji: '🌀', title: '혼돈대술사', personality: '초연한', element: 'DARK', archetype: 'MAGE', rarity: 'UR', signature: 'SIG_CHAOS_NOVA',
      lines: { greet: '혼돈이 내 부름에 응한다.', bond: '너만은 이 소용돌이 밖에 두마.', levelup: '봉인이 하나 풀렸다.' } },
    // ── 원형별 등급 공백 보강(N/R/SR/SSR/UR 전 등급 커버) ──
    { id: 'toren', name: '목순', emoji: '🔰', title: '풋내기방패', personality: '어리숙한', element: 'WOOD', archetype: 'VANGUARD', rarity: 'N', signature: 'SIG_VANGUARD_NOVICE',
      lines: { greet: '바, 방패는 자신 있습니다!', bond: '지켜드리겠습니다, 정말로요!', levelup: '조금은 든든해졌지요?' } },
    { id: 'kordan', name: '화벽', emoji: '🌋', title: '화염성벽', personality: '불굴의', element: 'FIRE', archetype: 'VANGUARD', rarity: 'SSR', signature: 'SIG_FLAME_BASTION',
      lines: { greet: '이 성벽은 무너지지 않는다.', bond: '내 불길 뒤에서 안심하라.', levelup: '화염이 더 거세진다!' } },
    { id: 'ymir', name: '빙제', emoji: '🏔️', title: '빙하거인', personality: '태고의', element: 'WATER', archetype: 'VANGUARD', rarity: 'UR', signature: 'SIG_GLACIAL_TITAN',
      lines: { greet: '태고의 한기가 깨어난다.', bond: '너를 위해 산이 되어주마.', levelup: '빙벽이 더 두꺼워진다.' } },
    { id: 'nella', name: '소화', emoji: '🌸', title: '견습사제', personality: '순수한', element: 'LIGHT', archetype: 'SUPPORT', rarity: 'N', signature: 'SIG_SUPPORT_NOVICE',
      lines: { greet: '기도가 닿기를…', bond: '당신을 위해 기도하겠어요.', levelup: '조금씩 힘이 늘어요.' } },
    { id: 'jax', name: '가랑', emoji: '🥋', title: '뒷골목칼잡이', personality: '거친', element: 'FIRE', archetype: 'ROGUE', rarity: 'R', signature: 'SIG_ALLEY_BLADE',
      lines: { greet: '어이, 조용히 끝내자.', bond: '너랑은 등 맞대도 되겠어.', levelup: '칼끝이 더 매서워졌다.' } },
    { id: 'mira', name: '무영', emoji: '🌫️', title: '안개자객', personality: '은밀한', element: 'WATER', archetype: 'ROGUE', rarity: 'SR', signature: 'SIG_MIST_STRIKE',
      lines: { greet: '안개가 짙어지는군.', bond: '너에겐 모습을 감추지 않아.', levelup: '자취를 더 잘 감출 수 있다.' } },
    { id: 'raven', name: '흑암', emoji: '🌑', title: '심연그림자', personality: '무자비한', element: 'DARK', archetype: 'ROGUE', rarity: 'UR', signature: 'SIG_ABYSS_SHADOW',
      lines: { greet: '그림자에 이름은 없다.', bond: '…너만은 벨 수 없군.', levelup: '어둠이 더 깊어졌다.' } },
    { id: 'finn', name: '소엽', emoji: '🍂', title: '견습사냥꾼', personality: '순박한', element: 'WOOD', archetype: 'ARCHER', rarity: 'N', signature: 'SIG_ARCHER_NOVICE',
      lines: { greet: '활 좀 다룰 줄 압니다!', bond: '같이 사냥 나가요!', levelup: '이제 손이 안 떨려요!' } },
    { id: 'lyra', name: '월시', emoji: '🌜', title: '월광궁수', personality: '냉철한', element: 'LIGHT', archetype: 'ARCHER', rarity: 'SR', signature: 'SIG_MOONLIGHT_SHOT',
      lines: { greet: '달빛 아래선 빗나가지 않는다.', bond: '너에게만 시위를 늦추지.', levelup: '조준이 더 매서워졌다.' } },
    { id: 'seren', name: '천응', emoji: '🦅', title: '천공대궁수', personality: '고고한', element: 'FIRE', archetype: 'ARCHER', rarity: 'UR', signature: 'SIG_CELESTIAL_ARROW',
      lines: { greet: '하늘 끝까지 꿰뚫는다.', bond: '네 곁에서만 활을 내린다.', levelup: '화살이 태양처럼 타오른다.' } },
    { id: 'pip', name: '소서', emoji: '📗', title: '견습술사', personality: '호기심 많은', element: 'WOOD', archetype: 'MAGE', rarity: 'N', signature: 'SIG_MAGE_NOVICE',
      lines: { greet: '이 술법, 성공할까요?', bond: '같이 술법 연습해요!', levelup: '오, 이번엔 안 터졌어요!' } },
    { id: 'thalia', name: '빙설', emoji: '🌬️', title: '빙결술사', personality: '차가운', element: 'WATER', archetype: 'MAGE', rarity: 'SR', signature: 'SIG_FROST_NOVA',
      lines: { greet: '…얼어붙을 준비는 됐나.', bond: '너에게만 온기를 남기지.', levelup: '한기가 더 짙어진다.' } },
    { id: 'nocturne', name: '야현', emoji: '🌘', title: '칠흑대현자', personality: '신비로운', element: 'DARK', archetype: 'MAGE', rarity: 'SSR', signature: 'SIG_VOID_SURGE',
      lines: { greet: '어둠의 지식이 속삭인다.', bond: '네게만 금서를 펼쳐 보이지.', levelup: '봉인된 지식이 흘러든다.' } },
  ],

  // 코스튬 — fantasy/scifi와 같은 구조(같은 캐릭터 id·해금·보너스), 무협 외형.
  costumes: {
    kael: { id: 'kael_c1', name: '홍염무복', emoji: '🥻', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    luna: { id: 'luna_c1', name: '월광선의', emoji: '🌙', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    gwen: { id: 'gwen_c1', name: '한빙갑주', emoji: '🛡️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    ciel: { id: 'ciel_c1', name: '표풍경장', emoji: '🌀', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    bran: { id: 'bran_c1', name: '중갑철의', emoji: '🏔️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    ael: { id: 'ael_c1', name: '예언도포', emoji: '🕊️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    ara: { id: 'ara_c1', name: '뇌전무복', emoji: '⚡', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    mir: { id: 'mir_c1', name: '수련경장', emoji: '🧵', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    pyra: { id: 'pyra_c1', name: '방열갑', emoji: '🔥', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    frost: { id: 'frost_c1', name: '극한설의', emoji: '❄️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    marina: { id: 'marina_c1', name: '벽수의복', emoji: '🌊', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    signe: { id: 'signe_c1', name: '전열군장', emoji: '🎺', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    aurel: { id: 'aurel_c1', name: '성광예복', emoji: '🌟', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    nyx: { id: 'nyx_c1', name: '심연도포', emoji: '🌌', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    kai: { id: 'kai_c1', name: '야행복', emoji: '🥷', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    vera: { id: 'vera_c1', name: '암야흑의', emoji: '🖤', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    robin: { id: 'robin_c1', name: '녹림엽장', emoji: '🍃', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    sylas: { id: 'sylas_c1', name: '광명궁의', emoji: '✨', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    elara: { id: 'elara_c1', name: '화령법의', emoji: '🔥', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    oriel: { id: 'oriel_c1', name: '혼돈도포', emoji: '🌌', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    toren: { id: 'toren_c1', name: '시제방패갑', emoji: '🔰', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    kordan: { id: 'kordan_c1', name: '용암갑주', emoji: '🌋', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    ymir: { id: 'ymir_c1', name: '고대빙갑', emoji: '🏔️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    nella: { id: 'nella_c1', name: '견습사제복', emoji: '🌸', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    jax: { id: 'jax_c1', name: '뒷골목흑의', emoji: '🥋', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    mira: { id: 'mira_c1', name: '연막경장', emoji: '🌫️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    raven: { id: 'raven_c1', name: '심연야의', emoji: '🌑', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    finn: { id: 'finn_c1', name: '견습엽복', emoji: '🍂', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    lyra: { id: 'lyra_c1', name: '월광궁의', emoji: '🌜', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    seren: { id: 'seren_c1', name: '천공저격의', emoji: '🦅', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    pip: { id: 'pip_c1', name: '견습법의', emoji: '📗', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    thalia: { id: 'thalia_c1', name: '빙결법의', emoji: '🌬️', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
    nocturne: { id: 'nocturne_c1', name: '칠흑현자의', emoji: '🌘', unlock: 5, bonus: { atk: 0.06, hp: 0.06, def: 0.06, spd: 0.06 } },
  },

  // 스토리 캠페인 — 같은 진행/전투 로직, 무협 서사로 교체.
  campaign: [
    { title: '객잔의 밤', story: '변방 객잔에 흉흉한 소문이 돈다. 첫 자객이 담을 넘고, 젊은 협객들이 검을 뽑는다.' },
    { title: '폐관의 문', story: '버려진 무관에 사기(邪氣)가 서렸다. 광증에 빠진 무인들이 침입자를 막아선다.' },
    { title: '한빙관', story: '얼어붙은 관문의 수호자가 길을 막는다. 낡은 계율만을 고집하는 냉혹한 검객.' },
    { title: '뇌전탑', story: '벼락이 탑을 휘감는다. 폭주한 기운이 관문을 넘으려는 자를 시험한다.' },
    { title: '양과 음', story: '중원의 기맥이 요동친다. 정도를 등진 술사가 음의 술법으로 일대를 장악했다.' },
    { title: '심층 동혈', story: '무림 심부의 봉인 동혈이 열린다. 흉신의 진원에서 무언가 깨어난다.' },
    { title: '맹주의 그림자', story: '무너진 맹의 전각에 정체 모를 존재가 도사린다. 강호를 삼키려는 자와의 대치.' },
    { title: '비급의 끝', story: '재앙의 핵심에서 마지막 초식이 형상을 갖춘다. 모든 인연과 내공을 걸고 최후의 일검을.' },
    // ── 2부: 잔재의 기운 ──
    { title: '잔재의 기운', story: '소멸시킨 줄 알았던 사기가 되살아난다. 강호의 상처는 아직 아물지 않았다.' },
    { title: '주화입마', story: '마기에 잠식된 옛 동문이 검을 겨눈다. 조준선을 겹치는 손이 무겁다.' },
    { title: '공허의 마존', story: '동혈 너머 심연에서 온 마존이 강림한다. 그 기운이 중원 전체를 잠식한다.' },
    { title: '여명일검', story: '재앙의 근원과 마주한다. 모든 것을 건 최후의 일검 — 강호에 여명이 밝는다.' },
  ],
};
